version: '3.3'
services:
  nginx:
    build:
      context: nginx
      dockerfile: .docker/Dockerfile
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
#      - 443:443 # HTTPS
#    volumes:
#      - ./php:/app

  php:
    build:
      context: php
      dockerfile: .docker/Dockerfile
    image: php:latest
    container_name: php
    working_dir: /app
    ports:
      - 9000:9000
    volumes:
      - ./php:/app
